In [1]:
import pandas as pd
import numpy as np
import konlpy
import sys
if sys.version_info <= (2,7):
    reload(sys)
    sys.setdefaultencoding('utf-8')
from konlpy.tag import Kkma, Okt, Hannanum
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
kkma = Kkma()
okt = Okt()
hannanum = Hannanum()


bal=pd.read_csv('data/melonbal.csv', encoding='cp949')
dan=pd.read_csv('data/melondan.csv', encoding='cp949')
hip=pd.read_csv('data/melonhip.csv', encoding='cp949')
rb=pd.read_csv('data/melonr_b.csv', encoding='cp949')
indi=pd.read_csv('data/melonindi.csv', encoding='cp949')
rock=pd.read_csv('data/melonrock.csv', encoding='cp949')
tst=pd.read_csv('data/melontwist.csv', encoding='cp949')
bf=pd.read_csv('data/melonbluefork.csv', encoding='cp949')

In [2]:
bal=bal.drop([' 제목'], axis=1)
bal=bal.drop(['랭크'], axis=1)
dan=dan.drop([' 제목'], axis=1)
dan=dan.drop(['랭크'], axis=1)
hip=hip.drop([' 제목'], axis=1)
hip=hip.drop(['랭크'], axis=1)
rb=rb.drop([' 제목'], axis=1)
rb=rb.drop(['랭크'], axis=1)
indi=indi.drop([' 제목'], axis=1)
indi=indi.drop(['랭크'], axis=1)
rock=rock.drop([' 제목'], axis=1)
rock=rock.drop(['랭크'], axis=1)
tst=tst.drop([' 제목'], axis=1)
tst=tst.drop(['랭크'], axis=1)
bf=bf.drop([' 제목'], axis=1)
bf=bf.drop(['랭크'], axis=1)

In [3]:
bal['genre']=1
dan['genre']=2
hip['genre']=3
rb['genre']=4
indi['genre']=5
rock['genre']=6
tst['genre']=7
bf['genre']=8

In [4]:
import csv
import random
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [23]:
train = pd.concat([bal, dan, hip, rock, tst, bf],join='inner')
train.to_csv('test.csv',encoding='CP949')

In [24]:
test = pd.read_csv('test.csv',header=0, encoding='CP949',error_bad_lines=False)
test = test.drop('Unnamed: 0',axis=1)
test

발매월  타입                                                 가사  genre
0      4.0  그룹  길었던 겨우내 줄곧 품이 좀 남는 밤색 코트 그 속에 나를 쏙 감추고 걸음을 재촉해...      1
1     12.0  솔로  월요일엔 아마 바쁘지 않을까 화요일도 성급해 보이지 안 그래 수요일은 뭔가 어정쩡한...      1
2      5.0  솔로  너의 그 한 마디 말도 그 웃음도 나에겐 커다란 의미 너의 그 작은 눈빛도 쓸쓸한 ...      1
3     10.0  솔로  어느새 길어진 그림자를 따라서 땅거미 진 어둠 속을 그대와 걷고 있네요 손을 마주잡...      1
4     11.0  그룹  니 생각에 꽤 즐겁고 니 생각에 퍽 외로워 이상한 일이야 누굴 좋아한단 건 아무 일...      1
...    ...  ..                                                ...    ...
1451  10.0  그룹  너무 오래 만난 것 같아 함께 있으면서 대화가 없어 이미 서로 많이 알아 버린 것 ...      8
1452   9.0  솔로  오늘도 그대는 여기에 있군요 똑같은 자리에 똑같은 가방이 어느새 찾아온 일상처럼 묘...      8
1453  12.0  솔로  저 들에 푸르른 솔잎을 보라 돌보는 사람도 하나 없는데 비바람 맞고 눈보라 쳐도 온...      8
1454  11.0  그룹  살며시 다가와 품에 안고 빛나는 사랑을 꿈꾸게 하네 살며시 다가와 입 맞추고 영원한...      8
1455   7.0  그룹  오늘은 분명히 날이 좋다 했는데 하나둘 몰려오는 구름 수상해 이런 날이면 괜히 느는...      8

[1456 rows x 4 columns]

In [28]:
X_data = test[['가사']]
Y_data = train['genre']

In [29]:
train_data = test[['가사']]
target_data = test[['genre']]
train_data=train_data.fillna(0)
train_data

가사
0     길었던 겨우내 줄곧 품이 좀 남는 밤색 코트 그 속에 나를 쏙 감추고 걸음을 재촉해...
1     월요일엔 아마 바쁘지 않을까 화요일도 성급해 보이지 안 그래 수요일은 뭔가 어정쩡한...
2     너의 그 한 마디 말도 그 웃음도 나에겐 커다란 의미 너의 그 작은 눈빛도 쓸쓸한 ...
3     어느새 길어진 그림자를 따라서 땅거미 진 어둠 속을 그대와 걷고 있네요 손을 마주잡...
4     니 생각에 꽤 즐겁고 니 생각에 퍽 외로워 이상한 일이야 누굴 좋아한단 건 아무 일...
...                                                 ...
1451  너무 오래 만난 것 같아 함께 있으면서 대화가 없어 이미 서로 많이 알아 버린 것 ...
1452  오늘도 그대는 여기에 있군요 똑같은 자리에 똑같은 가방이 어느새 찾아온 일상처럼 묘...
1453  저 들에 푸르른 솔잎을 보라 돌보는 사람도 하나 없는데 비바람 맞고 눈보라 쳐도 온...
1454  살며시 다가와 품에 안고 빛나는 사랑을 꿈꾸게 하네 살며시 다가와 입 맞추고 영원한...
1455  오늘은 분명히 날이 좋다 했는데 하나둘 몰려오는 구름 수상해 이런 날이면 괜히 느는...

[1456 rows x 1 columns]

In [30]:
matrix=[]
for lyrics in train_data['가사']:
    lyric_X = []
    lyric_X = okt.nouns(lyrics)
    matrix.append(lyric_X)

In [31]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
max_words = 35000
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(matrix)
sequences = tokenizer.texts_to_sequences(matrix)
train_data['가사'] =  sequences
print(max(len(l) for l in train_data['가사']))
print(sum(map(len,train_data['가사']))/len(train_data['가사']))

517
98.26923076923077


In [32]:
max_len = 517
data = pad_sequences(sequences, maxlen=max_len)
sequences=data

In [33]:
sequences

array([[   0,    0,    0, ...,  208,    3,  634],
       [   0,    0,    0, ...,  425,   19,  425],
       [   0,    0,    0, ...,  404,    4,  145],
       ...,
       [   0,    0,    0, ...,  440,  661,  440],
       [   0,    0,    0, ...,    3,    3,   33],
       [   0,    0,    0, ...,   90, 1852,  873]])

In [34]:
x_train,x_test,y_train,y_test = train_test_split(data,target_data,test_size=0.2)
x_test[0:5]

array([[   0,    0,    0, ...,   25,    3,   48],
       [   0,    0,    0, ...,  423, 1275,   88],
       [   0,    0,    0, ...,    6,    5,    2],
       [   0,    0,    0, ...,   57,    2,  145],
       [   0,    0,    0, ...,  177,   43,   37]])

In [35]:
y_test = np.array(y_test)
y_train = np.array(y_train)
x_train = np.array(list(x for x in x_train))
x_test = np.array(x_test)
y_train

array([[3],
       [6],
       [1],
       ...,
       [7],
       [7],
       [8]], dtype=int64)

In [36]:

from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(x_train,y_train)

print('training set accuracy:',tree.score(x_train, y_train))
print('test set accuracy:',tree.score(x_test,y_test))

prediction_by_tree = tree.predict(x_test)
prediction_by_tree

training set accuracy: 0.993127147766323
test set accuracy: 0.2465753424657534


array([8, 8, 8, 6, 6, 3, 2, 6, 8, 1, 7, 7, 3, 3, 3, 3, 1, 1, 7, 6, 6, 8,
       2, 7, 3, 6, 8, 2, 8, 3, 3, 8, 3, 8, 6, 8, 1, 1, 3, 6, 6, 7, 7, 2,
       1, 2, 2, 1, 1, 7, 3, 7, 1, 2, 3, 7, 8, 1, 6, 6, 2, 3, 1, 3, 6, 7,
       1, 7, 1, 1, 1, 2, 1, 6, 8, 6, 6, 2, 7, 7, 6, 6, 1, 6, 6, 7, 3, 3,
       2, 8, 7, 1, 2, 8, 3, 3, 8, 1, 6, 7, 2, 1, 7, 8, 7, 3, 1, 6, 6, 3,
       6, 3, 6, 8, 2, 1, 1, 1, 2, 8, 8, 7, 1, 7, 2, 8, 6, 6, 6, 7, 7, 3,
       6, 2, 7, 1, 8, 3, 8, 1, 3, 1, 3, 7, 8, 3, 1, 7, 6, 2, 2, 2, 7, 2,
       3, 8, 2, 2, 7, 7, 3, 7, 8, 8, 1, 7, 6, 8, 8, 8, 6, 7, 1, 8, 6, 2,
       3, 8, 6, 3, 6, 1, 6, 6, 2, 6, 1, 6, 7, 3, 3, 2, 6, 8, 6, 2, 6, 1,
       7, 7, 2, 3, 6, 6, 7, 7, 7, 1, 8, 3, 3, 7, 1, 7, 2, 1, 8, 2, 8, 1,
       7, 8, 1, 1, 8, 8, 8, 1, 2, 8, 8, 3, 6, 1, 1, 6, 7, 1, 1, 2, 8, 6,
       1, 6, 6, 1, 3, 6, 3, 1, 7, 6, 1, 3, 6, 2, 1, 1, 2, 8, 6, 2, 6, 6,
       1, 1, 1, 2, 1, 1, 2, 1, 6, 8, 7, 6, 2, 8, 2, 8, 1, 6, 3, 3, 6, 1,
       8, 2, 6, 8, 2, 6], dtype=int64)

In [37]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=10)
forest.fit(x_train,y_train)

print('training set accuracy:',forest.score(x_train,y_train))
print('test set accuracy:',forest.score(x_test,y_test))

prediction_by_forest = forest.predict(x_test)
prediction_by_forest

training set accuracy: 0.9853951890034365
test set accuracy: 0.3047945205479452


C:\anaconda\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


array([3, 6, 2, 8, 6, 2, 3, 2, 7, 6, 7, 7, 3, 2, 8, 3, 3, 1, 3, 2, 1, 7,
       3, 6, 1, 1, 8, 1, 8, 3, 3, 6, 3, 2, 6, 1, 6, 3, 8, 7, 1, 8, 7, 3,
       6, 8, 3, 1, 6, 7, 8, 7, 1, 6, 8, 6, 3, 1, 1, 6, 3, 2, 6, 3, 1, 8,
       1, 8, 6, 2, 1, 7, 3, 6, 1, 2, 7, 8, 7, 8, 1, 6, 1, 7, 1, 8, 3, 3,
       2, 1, 7, 6, 1, 7, 3, 3, 6, 1, 1, 7, 2, 7, 7, 2, 7, 3, 1, 6, 8, 2,
       6, 2, 2, 7, 2, 1, 1, 8, 1, 8, 7, 6, 3, 8, 1, 7, 2, 7, 6, 3, 7, 2,
       1, 3, 8, 6, 8, 3, 1, 1, 1, 6, 1, 7, 8, 3, 1, 2, 6, 2, 3, 2, 7, 2,
       3, 8, 2, 1, 1, 7, 1, 7, 7, 1, 8, 6, 6, 6, 2, 6, 1, 7, 8, 6, 1, 2,
       2, 7, 1, 2, 3, 1, 7, 1, 3, 2, 2, 1, 6, 1, 3, 2, 6, 1, 6, 3, 7, 1,
       8, 8, 2, 1, 1, 6, 8, 7, 7, 6, 7, 3, 1, 8, 7, 7, 2, 1, 7, 2, 6, 3,
       1, 2, 6, 6, 2, 7, 7, 1, 1, 2, 2, 3, 7, 1, 7, 6, 6, 8, 7, 2, 6, 3,
       8, 6, 1, 2, 8, 6, 3, 7, 7, 6, 3, 2, 7, 2, 8, 1, 3, 1, 6, 3, 6, 7,
       1, 2, 2, 3, 1, 6, 1, 2, 6, 1, 7, 7, 6, 1, 2, 6, 6, 8, 2, 3, 1, 8,
       7, 1, 6, 8, 3, 3], dtype=int64)